FROM node:10
RUN mkdir -p /app/backend/ 
WORKDIR /app/backend/
COPY package*.json /app/backend/
RUN npm install

ARG MONGO_PROTOCOL_ARG=mongodb 
ENV MONGO_PROTOCOL=$MONGO_PROTOCOL_ARG

ARG MONGO_HOSTNAME_ARG=codingtips-db 
ENV MONGO_HOSTNAME=$MONGO_HOSTNAME_ARG

ARG MONGO_PORT_ARG=27017 
ENV MONGO_PORT=$MONGO_PORT_ARG

ARG MONGO_DB_ARG=codingtips-db 
ENV MONGO_DB=$MONGO_DB_ARG

ARG MONGO_USERNAME_ARG= 
ENV MONGO_USERNAME=$MONGO_USERNAME_ARG

ARG MONGO_PASSWORD_ARG= 
ENV MONGO_PASSWORD=$MONGO_PASSWORD_ARG

# Bundle app source
COPY . /app/backend/
EXPOSE 3000
CMD [ "npm", "start" ]
